services:
  demo-app-dev:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - './app:/workspace'
      - demo-app-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true
    container_name: demo-app-dev
  k3s:
    image: "rancher/k3s:v1.29.3-k3s1"
    hostname: k3s
    command: server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    environment:
    - K3S_TOKEN=HL7i5g88DEsMGt
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    # cp ./data/output/kubeconfig.yaml ~/.kube/config
    volumes:
    - ./k3s/data/k3s-server1:/var/lib/rancher/k3s

    - ./k3s/data/logs:/logs/access.log
    # This is just so that we get the kubeconfig file out
    - ./k3s/data/output:/output
    - ./k3s/config/traefik-config.yaml:/var/lib/rancher/k3s/server/manifests/traefik-config.yaml
    # ports:
    # - 6443:6443  # Kubernetes API Server
    # - 80:80      # Ingress controller port 80
    # - 443:443    # Ingress controller port 443
    # network_mode: host
    healthcheck:
      test: ["CMD", "kubectl", "get", "nodes"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

  control-dev:
    build:
      context: ./control
      dockerfile: Dockerfile.dev
    volumes:
      - './:/workspace'
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - control-dev-vsc:/root/.vscode-server
      - control-dev-rye:/root/rye

    stdin_open: true
    tty: true
    container_name: control-dev

  k3s-setup-dev:
    build:
      context: ./k3s-setup
      dockerfile: Dockerfile.dev
    volumes:
      - './:/workspace'
      - k3s-setup-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true
    container_name: k3s-setup-dev

  kubepi:
    image: '1panel/kubepi'
    container_name: kubepi
    ports:
      - 8081:80
    volumes:
      - ./kubepi/data:/var/lib/kubepi

volumes:
  control-dev-vsc:
  control-dev-rye:
  k3s-setup-dev-vsc:
  demo-app-dev-vsc: