# https://github.com/traefik/traefik-helm-chart
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: 2.10.5
    additionalArguments:
      - --log.level=DEBUG
      - --api.insecure=true
      - --accesslog=true